config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'landing#index'
  get 'landing' => 'landing#index'

  resources :categories
  resources :products
  get 'signup'  => 'users#new'
  resources :users
  get 'search' => 'landing#search', as: 'search'
  get 'search_results' => 'landing#search_results', as: 'search_results'
  get 'category' => 'categories#category', as: 'prod_category'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :products


end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, :condition, :picture, presence: true
  validates :price, numericality: {greater_than: 0}

  belongs_to :user
  belongs_to :categories
  CONDITION = ["New", "Used"]
  def formatted_price
  if price % 100 == 0
    "$#{price / 100}"
  else
  price_in_dollars = price.to_f / 100
  format("$%.2f", price_in_dollars)
end
end
  def self.keyword_search(keywords)
    keywords = "%" + keywords + "%"
    Product.where("name LIKE ? OR description LIKE ?", keywords, keywords)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}

  has_many :products

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
    def show
     @product = Product.find(params[:id])

     respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @product }
     end
   end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @categories = Category.order(:name)
  end

  def search

  end

  def search_results
    @found_products = Product.keyword_search(params[:search_keywords])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def categories
    @categories = Category.order(:name)
end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)
    @product.price *= 100
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :condition, :picture, :price)
    end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @categories = Category.order(:name)
  end

  def search

  end

  def search_results
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="grid">
<% @category.products.each do |product| %>
<figure class="effect-lexi">
<%= image_tag product.picture, height: '293', width: '480' %>
  <figcaption>
    <h2><%= link_to product.name, product%></h2>
    <p><%= product.description %><br><%= link_to product.formatted_price, product %></p>

  </figcaption>
</figure>
<%end%>

</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

<a href= "/products/new" alt="#"><h2>Sell Something</h2></a>

<div class="grid">

                 <% Product.all.each do |pic| %>
                 <figure class="effect-lexi">
                 <%= image_tag pic.picture, height: '293', width: '480' %>
                   <figcaption>
                     <h2><%= link_to pic.name, pic%></h2>
                     <p><%= pic.description %><br><%= link_to pic.formatted_price, pic %></p>
                     <!-- <p><%= link_to pic.formatted_price, pic %></p> -->

                   </figcaption>
                 </figure>
                 <%end%>

               </div>

app/views/landing/search.html.erb
<h2>Search</h2>

<%= form_tag search_results_path, method: 'get' do %>
<%= text_field_tag :search_keywords %>
<%= submit_tag "Search" %>
<% end %>

app/views/landing/search_results.html.erb
<% if @found_products.empty? %>
 <p>No results found</p>
 <%end%>

<%= render partial: 'products/product', collection: @found_products %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wynbay.com</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="">

  <!-- Bootstrap Core CSS -->

  <!-- Custom CSS -->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>
    <div id="wrapper">
        <div id="header">
            <p>This is the Header</p>
        </div>
        <div id="navigation">
          <ul id="menu-bar">
 <li class="active"><%=link_to 'Home', landing_path%></li>
 <li><a href="#">Categories</a>
  <ul>
    <% Category.order(:name).each do |category| %>

   <li><%=link_to category.name, category%></li>
   <%end%>
  </ul>
 </li>
 <li class="search-form"><%= form_tag search_results_path, method: 'get' do %> <!-- search bar -->
   <%= text_field_tag :search_keywords %>
   <%= submit_tag "Search" %>
   <% end %></li>

<li><p></p></li>

<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>
<li><p></p></li>


   <% if user_signed_in? %>
 <li><%= link_to "New Product", new_product_path %></li>
 <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
 <% else %>
 <li><%= link_to "Sign In", new_user_session_path %></li>
 <li><%= link_to "Sign Up", new_user_registration_path %></li>
<%end%>
</ul>
        </div>
        <div id="contentliquid"><div id="content">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      <%= yield %>
       </div></div>
        <div id="footer">
            <p>This is the Footer</p>
        </div>
    </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class= "field">
    <%= f.label :category_id %><br>
  <%= f.select :category_id, Category.all.map{|c| [c.name, c.id, {class: c.id }]}, :include_blank => true  %>
  </div>
  <div class= "field">
    <%= f.label :condition %><br>
  <%= f.select :condition, Product::CONDITION, :include_blank => true  %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<section text-align= "left">
  <p><%= image_tag product.picture %></p>
  <h3><%= link_to product.name, product %></h3>
  <p>description: <%= product.description %>
    <p>Condition: <%= product.condition %></p>
    <p>Category: <%= Category.where(id: product.category_id).first.name %></p>
    <p>Price: <%= product.formatted_price %></p>
    <% if product.user == current_user %>
    <p><%= link_to 'Edit', edit_product_path(product) %></p>
    <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <%end%>
    <br>
  </section>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<h2>Products</h2>
<!-- <% @products.each do |product| %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Category</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.condition %></td>
        <td><%= Category.where(id: product.category_id).first.name %></td>
        <td><%= product.picture %></td>
        <td><%= product.formatted_price %></td>
        <td><%= link_to 'Show', product %></td>
        <% if product.user == current_user %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
  </tbody>
</table>
<% end %> -->
 <!-- <% @products.each do |product| %>
<section text-align= "left">
  <h3><%= link_to product.name, product %></h3>
    <p>description: <%= product.description %>
      <p>Condition: <%= product.condition %></p>
      <p>Category: <%= Category.where(id: product.category_id).first.name %></p>
      <p>Picture: <%= product.picture %></p>
      <p>Price: <%= product.formatted_price %></p>
      <p><%= link_to 'Show', product %></p>
      <% if product.user == current_user %>
      <p><%= link_to 'Edit', edit_product_path(product) %></p>
      <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <%end%>
      <%end%>

<br> -->

 <!-- <% @products.each do |product| %> -->
 <%= render @products %>
<% end %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @product %>
<!--
<div>
		<%= image_tag @product.picture %>
</div>


<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Condition:</strong>
  <%= @product.condition %>
</p>

<p>
  <strong>Seller Email:</strong>
  <%= @product.user.email %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.formatted_price %>
</p> -->
<% if @product.user == current_user %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%end%>

<%= link_to 'Home', landing_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>